services:
  db:
    image: postgres:15-alpine
    container_name: orders_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: orders_web
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
    volumes:
      - .:/app
    working_dir: /app/orders
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "sleep 5 && 
             python manage.py migrate --noinput && 
             python manage.py runserver 0.0.0.0:8000"
  redis:
    image: redis:7-alpine
    container_name: orders_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  
  celery_worker:
    build: .
    container_name: orders_celery_worker
    restart: always
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - .:/app
    working_dir: /app/orders
    depends_on:
      - redis
      - db
      - web
    command: >
      sh -c "sleep 10 &&
             celery -A orders worker --loglevel=info --concurrency=2"
  
  celery_beat:
    build: .
    container_name: orders_celery_beat
    restart: always
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - .:/app
    working_dir: /app/orders
    depends_on:
      - redis
      - db
      - web
    command: >
      sh -c "sleep 15 &&
             celery -A orders beat --loglevel=info"
  
  flower:
    image: mher/flower:1.2
    container_name: orders_flower
    restart: always
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      FLOWER_PORT: 5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker

  tests:
    build: .
    container_name: orders_tests
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: 'True'
      CELERY_BROKER_URL: memory://  # Для тестов используем memory broker
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    command: >
      sh -c "cd orders &&
             python manage.py migrate --noinput &&
             coverage run -m pytest backend/tests/ -v &&
             coverage report --fail-under=30"

volumes:
  postgres_data:
  redis_data:

